Game logic of tic tac toe
rammazzoti2000/tic-toc-toe pull request #3
Opened 2020-03-18 13:33 UTC by jaspreet-singh-sahota

## Just for we have changed the token "X" and "O" to "rum" and "vodka"
- This is modern Tic Tac Toe.
- Try running wrong arguments first. And have fun.
- Waiting for your feedback.

2020-03-18 15:47 UTC, MauricioRobayo requested changes
Very nice project, I had a lot of fun playing with it, well done!

We need to fix some issues before continuing:

* [x] Do not make any changes in [config files](https://github.com/microverseinc/linters-config/tree/master/ruby) - they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/))
* [x] Please fix Stickler/Rubocop issues.
* [x] No `puts/print` and `get.chomp` outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [x] Use attr_readers/attr_writers instead of attr_accessors when possible to avoid writing that property from outside the class  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/attr_accessor.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)).
* [x] Avoid global variables, it breaks the OOP encapsulation principle: https://www.thoughtco.com/global-variables-2908384.

Status: __Request changes__.

---

Optional:

* The board looks a little misaligned which makes it difficult to follow:

![image](https://user-images.githubusercontent.com/2121481/76979610-2d5cd400-6906-11ea-8078-4abfaaff7ace.png)

2020-03-18 15:47 UTC, MauricioRobayo commented on lib/position.rb
> +  attr_accessor :get_position
Use `attr_reader` instead of `attr_accessor` is you are only going to read, not write, the variable. Check your use of `attr_accessor`.

2020-03-18 15:47 UTC, MauricioRobayo commented on lib/position.rb
> +      puts 'Error, invaild input!!! Choose a Number between 1 - 9'
No `puts/print` and `get.chomp` outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

2020-03-18 22:40 UTC, pelzolga123 requested changes
Project requires changes.

2020-03-18 22:41 UTC, pelzolga123 commented
## Hi Team! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Your project looks amazing, good job so far :+1: 
Still, you need to make some more changes before this project can be approved:

* [ ] All linter errors should be fixed. 
* [ ] You removed board class after first review, that's not very good. The project should use at least two classes. The code of the project should be logically divided between classes. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/classes.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [ ] Stickler should not ignore `bin` folder. As previous review asked you should not make any changes in config files .

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-03-18 23:16 UTC, rammazzoti2000 commented
Hello @pelzolga123, thank you for the feedback, very helpful.
Completed all the required changes, wait for your feedback, thank you.

2020-03-19 14:30 UTC, MauricioRobayo approved these changes
This is it, you got it!

Congratulations, please move on.

Status: __Approved__.

2020-03-19 14:30 UTC, merged